version: "3"
services:
    db:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - "9999:5432"
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "adminpw"
        volumes:
            - ./data/:/var/lib/postgresql/data